#Define the version of docker compose 
version: '3'

# Define different containers that you want to run
services:
  #Define container name 
  redis-server:
    #Define container image
    image: 'redis'
  node-app:
    #Define when the container will restart again options are(always, on-failure,on-stop)
    restart: always

    #Specify the Dockerfile in the current working directory that will be build 
    build: .

    #Specify the port mapping
    ports:
      - "4001:8081"
